name: GitHub Actions Demo
run-name: Make ECR Registry 🚀
on: [workflow_dispatch]
jobs:
  Make-ECR-Registry:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: 'arn:aws:iam::767397855647:role/remix-quiz-oidc-role'
      - run: aws ecr create-repository --repository-name test_from_gha --region ap-northeast-1
